spring.datasource.url=jdbc:postgresql://localhost:5432/beautybuddy
spring.datasource.username=postgres
spring.datasource.password=Chester2010!

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:seed.sql