spring.datasource.url=jdbc:postgresql://localhost:5432/beautybuddy
spring.datasource.username=postgres
spring.datasource.password=Chester2010!

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.sql.init.mode=never