services:
  backend_blue:
    image: ghcr.io/marikascrepnek/beautybuddy-backend:latest
    ports:
      - "8081:8080"
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  backend_green:
    image: ghcr.io/marikascrepnek/beautybuddy-backend:latest
    ports:
      - "8082:8080"
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    
    logging:
      options:
        max-size: "10m"
        max-file: "3"


  frontend:
    image: ghcr.io/marikascrepnek/beautybuddy-frontend:latest
    ports:
      - "3000:80"
    restart: unless-stopped

  db:
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped

    logging:
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data

    logging:
      options:
        max-size: "10m"
        max-file: "3"

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    restart: unless-stopped

volumes:
  postgres-data:
  redis-data: