name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_BACKEND: marikascrepnek/beautybuddy-backend
  IMAGE_NAME_FRONTEND: marikascrepnek/beautybuddy-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # ---------------- BACKEND ----------------
      - name: Build backend image
        run: |
          docker build \
            -t $REGISTRY/$IMAGE_NAME_BACKEND:${{ github.sha }} \
            ./BeautyBuddy-backend

      - name: Push backend image
        run: |
          docker push $REGISTRY/$IMAGE_NAME_BACKEND:${{ github.sha }}

      # ---------------- FRONTEND ----------------
      - name: Build frontend image
        run: |
          docker build \
            -t $REGISTRY/$IMAGE_NAME_FRONTEND:${{ github.sha }} \
            ./BeautyBuddy-frontend

      - name: Push frontend image
        run: |
          docker push $REGISTRY/$IMAGE_NAME_FRONTEND:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/BeautyBuddy

            export TAG=${{ github.sha }}

            echo "Deploying version: $TAG"

            # Pull images
            docker pull ghcr.io/marikascrepnek/beautybuddy-backend:$TAG
            docker pull ghcr.io/marikascrepnek/beautybuddy-frontend:$TAG

            # STEP 1: Deploy GREEN (inactive target)
            TAG=$TAG docker compose -p beautybuddy -f docker-compose.prod.yml up -d backend_green

            # STEP 2: Wait for GREEN health
            timeout 60 bash -c 'until curl -fs http://localhost:8082/actuator/health; do sleep 2; done'

            echo "Switching traffic to GREEN"

            # STEP 3: SWITCH NGINX (8081 → 8082)
            sudo sed -i 's/8081/8082/' /etc/nginx/sites-enabled/beautybuddy
            sudo nginx -s reload

            # STEP 4: Stop BLUE (old version)
            docker compose -p beautybuddy -f docker-compose.prod.yml stop backend_blue

            # STEP 5: Start BLUE as standby for next deploy
            TAG=$TAG docker compose -p beautybuddy -f docker-compose.prod.yml up -d backend_blue

            # STEP 6: Wait for BLUE warm standby
            timeout 60 bash -c 'until curl -fs http://localhost:8081/actuator/health; do sleep 2; done'

            # cleanup
            docker image prune -f